export const fieldAliases = {
    "objectid": "Object ID",
    "parno": "Parcel Number",
    "altparno": "Alternate Parcel Number",
    "ownname": "Owner Name",
    "improvval": "Improved Value",
    "landval": "Land Value",
    "parval": "Parcel Value",
    "mailadd": "Mailing Address",
    "munit": "Mailing Address Unit Number",
    "mcity": "Mailing Address City",
    "mstate": "Mailing Address State",
    "mzip": "Mailing Address Zip",
    "siteadd": "Full Site Address",
    "sunit": "Site Address Unit Number",
    "scity": "Site Address City",
    "gisacres": "GIS Acres",
    "struct": "Structure Indicator",
    "multistruc": "Multiple Structures",
    "saledate": "Last Sale Date",
    "saledatetx": "Last Sale Date Text",
    "legdecfull": "Full Legal Description",
    "parusecode": "Tax Parcel Use Code",
    "parusedesc": "Tax Parcel Use Code Description",
    "parusecd2": "Second Tax Parcel Use Code",
    "parusedsc2": "Second Tax Parcel Use Description",
    "parvaltype": "Type of Value Reported",
    "owntype": "Owner Type",
    "recareano": "Record Area Number",
    "recareatx": "Record Area Text",
    "revisedate": "Revised Date",
    "sourceref": "Source Document Reference",
    "sourcedate": "Source Document Date",
    "sourcedatx": "Source Document Date Text",
    "subdivisio": "Subdivision Name",
    "nparno": "National Parcel Number",
    "cntyname": "County Name",
    "cntyfips": "County FIPS Code",
    "stfips": "State FIPS Code",
    "stcntyfips": "State-County FIPS Code",
    "gnisid": "GNIS Identifier",
    "sourceagnt": "Information Source",
    "transfdate": "Transform Date",
    "maddpref": "Mailing Address Prefix",
    "maddrno": "Mailing Address Number",
    "maddstname": "Mailing Street Full Name",
    "maddstr": "Mailing Address Street Name",
    "maddstsuf": "Mailing Address Street Suffix",
    "maddsttyp": "Mailing Address Street Type",
    "ownfrst": "Owner First Name",
    "ownlast": "Owner Last Name",
    "revdatetx": "Revised Date text",
    "reviseyear": "Revised Year",
    "saddno": "Site Address Number",
    "saddpref": "Site Address Prefix",
    "saddstname": "Site Address Street Name",
    "saddstr": "Site Address Street Name",
    "saddstsuf": "Site Address Street Suffix",
    "saddsttyp": "Site Address Street Type",
    "sstate": "Site Address State",
    "stname": "State Name",
    "subowntype": "Subsurface Owner Type",
    "subsurfown": "Subsurface Owner",
    "szip": "Site Address Zip",
    "structno": "Number of Structures",
    "structyear": "Structure Year",
    "ownname2": "Full Second Owner Name",
    "presentval": "Present Use Value",
    "mapref": "Map Reference"
};

export const countyGISMap = {
    "Wake": "https://maps.raleighnc.gov/iMAPS/",
    "Guilford": "https://gisdv.guilfordcountync.gov/Guilford/",
    "Johnston": "https://mapclick6.johnstonnc.com/mapclick6/index.html/?app=mapclick&ui=mapclick4"
}